[package]
name = "polyline"
description = "Encoder and decoder for the Google Encoded Polyline format"
version = "0.5.0"
authors = ["Tom MacWright <tom@macwright.org>"]
repository = "https://github.com/georust/rust-polyline"
readme = "README.md"
keywords = ["polyline", "geo"]
license = "ISC"

[dependencies]
rand = "0.5.0"
