[package]
name = "node"
version = "0.1.0"
authors = ["Tom MacWright <tom@macwright.org>"]
license = "MIT"

[lib]
name = "node"
crate-type = ["dylib"]

[dependencies]
neon = "0.1.10"
polyline = "0.1.0"
